"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-01
"""

from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("roles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(80), nullable=False, unique=True), sa.Column("description", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("permissions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(120), nullable=False, unique=True), sa.Column("description", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("username", sa.String(80), nullable=False, unique=True), sa.Column("full_name", sa.String(200)), sa.Column("hashed_password", sa.String(255), nullable=False), sa.Column("is_active", sa.Boolean(), default=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("role_permissions", sa.Column("role_id", sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True), sa.Column("permission_id", sa.ForeignKey("permissions.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("user_roles", sa.Column("user_id", sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True), sa.Column("role_id", sa.ForeignKey("roles.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("partners", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("code", sa.String(80), unique=True), sa.Column("tax_id", sa.String(80)), sa.Column("phone", sa.String(80)), sa.Column("email", sa.String(255)), sa.Column("address", sa.Text()), sa.Column("is_active", sa.Boolean(), default=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("product_groups", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("parent_id", sa.ForeignKey("product_groups.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("units", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(80), nullable=False, unique=True), sa.Column("short_name", sa.String(20), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("warehouses", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("address", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("currencies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(3), nullable=False, unique=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("products", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("sku", sa.String(80), unique=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("group_id", sa.ForeignKey("product_groups.id")), sa.Column("unit_id", sa.ForeignKey("units.id")), sa.Column("base_price", sa.Numeric(14, 2)), sa.Column("is_active", sa.Boolean(), default=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("documents", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_type", sa.String(60), nullable=False), sa.Column("number", sa.String(80)), sa.Column("document_date", sa.Date(), nullable=False), sa.Column("status", sa.String(40), nullable=False, server_default="draft"), sa.Column("partner_id", sa.ForeignKey("partners.id")), sa.Column("warehouse_id", sa.ForeignKey("warehouses.id")), sa.Column("total_amount", sa.Numeric(14, 2), server_default="0"), sa.Column("note", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("document_lines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.ForeignKey("documents.id", ondelete="CASCADE"), nullable=False), sa.Column("product_id", sa.ForeignKey("products.id"), nullable=False), sa.Column("quantity", sa.Numeric(14, 3), nullable=False), sa.Column("price", sa.Numeric(14, 2), nullable=False), sa.Column("line_total", sa.Numeric(14, 2), server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("stock_movements", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("product_id", sa.ForeignKey("products.id"), nullable=False), sa.Column("warehouse_id", sa.ForeignKey("warehouses.id"), nullable=False), sa.Column("document_id", sa.ForeignKey("documents.id")), sa.Column("quantity_delta", sa.Numeric(14, 3), nullable=False), sa.Column("reason", sa.String(120)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("stock_balances", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("product_id", sa.ForeignKey("products.id"), nullable=False), sa.Column("warehouse_id", sa.ForeignKey("warehouses.id"), nullable=False), sa.Column("quantity", sa.Numeric(14, 3), server_default="0"), sa.UniqueConstraint("product_id", "warehouse_id", name="uq_stock_balance_product_warehouse"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("prices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("product_id", sa.ForeignKey("products.id"), nullable=False), sa.Column("currency_id", sa.ForeignKey("currencies.id")), sa.Column("amount", sa.Numeric(14, 2), nullable=False), sa.Column("valid_from", sa.Date()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("payments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("partner_id", sa.ForeignKey("partners.id")), sa.Column("document_id", sa.ForeignKey("documents.id")), sa.Column("payment_date", sa.Date(), nullable=False), sa.Column("amount", sa.Numeric(14, 2), nullable=False), sa.Column("method", sa.String(80)), sa.Column("note", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("cash_operations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("operation_date", sa.Date(), nullable=False), sa.Column("direction", sa.String(20), nullable=False), sa.Column("amount", sa.Numeric(14, 2), nullable=False), sa.Column("partner_id", sa.ForeignKey("partners.id")), sa.Column("document_id", sa.ForeignKey("documents.id")), sa.Column("note", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("audit_log", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("actor_user_id", sa.ForeignKey("users.id")), sa.Column("entity_type", sa.String(120), nullable=False), sa.Column("entity_id", sa.String(80), nullable=False), sa.Column("action", sa.String(80), nullable=False), sa.Column("details", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))


def downgrade() -> None:
    for table in ["audit_log", "cash_operations", "payments", "prices", "stock_balances", "stock_movements", "document_lines", "documents", "products", "currencies", "warehouses", "units", "product_groups", "partners", "user_roles", "role_permissions", "users", "permissions", "roles"]:
        op.drop_table(table)
